services:
  - type: web
    name: oddsapiio-backend
    runtime: java
    plan: free
    buildCommand: mvn package -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: ODDS_API_KEY
        sync: false
